### PR TITLE
Add extended normalisation options

### PR DESCRIPTION
**Pull request by auricgoldfinger**
I added some modifications to your magnificent program to automatically normalize several media files at once.
I added some modifications to perfectly match my needs and I wanted to share those with you. It's not a request to you to add all of these features, it's just that some of them might be handy for other users as well.
- add program option to write output in a separate directory in stead of prefixing it, making it easier to handle the modfied files.
- add program option to merge the normalized audio in the original (video) file rather than creating a separate WAV file
- change the maximum setting: will now normalize so that max. **This is one that you might want to review. I wanted the option to handle the audio using the maximum volume**
   e.g. : -m -l -5 will increase the audio level to max = -5.0dB
- improve verbose logging: number of files are written to the info log and I changed some "warning" loggings to "info" loggings
- improve performance: check first whether the output file exists before calculating the volume levels + not modifying the file if the adjustment < 0.5dB (level is never exactly 0 so if you run the app twice, most files will be processed while none of them are actually modified)

### CODE REVIEW

**Comment by benjaoming** [comment]
:+1:

**Comment by slhck** [comment]
This looks great, thank you!

The only thing I'm not a 100% sure about is that with the merging command, there's no control over what kind of encoder will be used for the output file — it's basically up to ffmpeg to decide, and there is no way to pass additional encoding options. Now, merging is optional, I know, but if there was an option to specify the audio codec and audio options, that'd make it even more useful. Just not sure how this would be best implemented (in terms of command-line syntax).

But I guess I'll pull this after having a look at it tomorrow.

**Comment by michaelcrossland** [comment]
where can I find this new code at? As most of it is what I'm trying to mod in myself and having 0 luck.

**Comment by auricgoldfinger** [comment]
@slhck It's true that I don't pass additional encoding options because (I assume) ffmpeg will copy the original audio codecs as well by passing the `-vcodec copy` param. This way, I don't have to care about the audio encoding in the original video. It might be a good idea to add `-acodec copy` as well but I'm unsure whether the filter will then work. Note that I have used the shortcodes: `-af` short is for `-filter:a` etc.

Remark: while reviewing the patch I noticed I was handling the following issue: When the app is trying to normalize a file that is corrupt in one way or the other, an error is generated and the process is killed. I was trying to catch that, throw an error and continue with the next file in the queue. I didn't succeed/finish this modification, but that's why lines 148 and 155 were changed and the `try: except:` block on 168

**Comment by slhck** [comment]
> (I assume) ffmpeg will copy the original audio codecs as well by passing the -vcodec copy param. 

It's not possible to apply an audio filter and copy the bitstream at the same time. ffmpeg will choose some default (usually rather low quality) audio options instead. I'll think about some way to add a codec option and some additional options passed to ffmpeg, for example:

    ffmpeg-normalize ... --acodec libfdk_aac --ffmpeg-options "-b:a 192k"

**Comment by slhck** [comment]
@michaelcrossland You can expect a new release tonight (CET), with all these changes added.

**Comment by slhck** [comment]
New version pushed to PyPI, thanks everyone for your help on this, especially @auricgoldfinger.

**Comment by auricgoldfinger** [comment]
Glad I could help!

**Pull request merged**
