### PR TITLE
Rename project

### PR DESCRIPTION
**Pull request by benjaoming**
Fix for comment in #2

### CODE REVIEW

**Comment by slhck** [comment]
I did some touchups on the README and HISTORY, should be fine now!

**Comment by benjaoming** [comment]
Oh yes, forgot those, great, so I'll pull in your changes, put it on pypi and delete the avconv one :)

**Comment by slhck** [comment]
Sounds great, thanks for your efforts! Ping me when it's done and I will update the Super User post using the new link.

**Comment by benjaoming** [comment]
New link!

https://pypi.python.org/pypi/ffmpeg-normalize/

**Comment by slhck** [comment]
Awesome, thanks! Everything updated on SU as well.

**Pull request merged**
