### PR TITLE
Docopt, Setuptools, avconv compatibility

### PR DESCRIPTION
**Pull request by benjaoming**
I can put this script on PyPi now if you like -- or you can do it yourself! :)

    python setup.py register
    python setup.py sdist upload [--sign]

That will do the trick.

Hope you like the improvements, thanks for the project.

### CODE REVIEW

**Comment by benjaoming** [comment]
Btw it works on Python 3

**Comment by slhck** [comment]
Awesome, thanks! Let me pull this later today!

**Comment by slhck** [comment]
I'm not on a computer, so if you want, feel free to upload it!

**Comment by benjaoming** [comment]
Btw I would recommend that you put it on PyPi yourself, I know almost nothing about ffmpeg, I was just cleaning up the script to support avconv a slight bit... some of the options are not actually implemented for avconv.

**Comment by slhck** [comment]
Oh okay. Will do, thanks!

**Comment by benjaoming** [comment]
Cool, you can find it here:

https://pypi.python.org/pypi/avconv-normalize

Send me your username on PyPi and I'll make sure to add you as admin!

**Comment by slhck** [comment]
I'm `slhck` there, too.

I just had a bit of a closer look. To be honest I am not too happy with the name `avconv` because the tool relies on `ffmpeg` and those are [quite different](http://stackoverflow.com/questions/9477115/what-are-the-differences-and-similarities-between-ffmpeg-libav-and-avconv).

Do you think you could rename everything to `audio-normalize` as originally created by me when I made this script? That'd make it more easily searchable, too, and it wouldn't imply a dependency on avconv, especially if it's not working with avconv as expected—even the README says `ffmpeg`.

I can make the commits here in order to rename it, too, just let me know.

**Comment by benjaoming** [comment]
That's a good question!! I was under the impression that ffmpeg was being replaced by libav and avconv -- but that was something I didn't even research!

It seems that ffmpeg was abandoned for Debian and Ubuntu around when Jessie and 14.04 + 14.10 were released. But it's been back since 15.04 and is in Debian testing and unstable again.

Would you like if we name the project ffmpeg-normalize ? I think it'd be cool to have "ffmpeg" in the name, because its so tightly coupled to it.

**Comment by slhck** [comment]
Yeah, that'd make much more sense! I

('m also not quite happy with the way avconv was put into Ubuntu, making it sound like ffmpeg was dead, which it certainly isn't.)

**Pull request merged**
